server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@10.144.118.70:1521/payment
    username: recon_statement
    password: recon_statement2021
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
